//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Core.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Store.Core.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be 0!.
        /// </summary>
        public static string @__0___cannot_be_0_ {
            get {
                return ResourceManager.GetString("\'{0}\' cannot be 0!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be empty!.
        /// </summary>
        public static string @__0___cannot_be_empty_ {
            get {
                return ResourceManager.GetString("\'{0}\' cannot be empty!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be null!.
        /// </summary>
        public static string @__0___cannot_be_null_ {
            get {
                return ResourceManager.GetString("\'{0}\' cannot be null!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is required!.
        /// </summary>
        public static string @__0___is_required_ {
            get {
                return ResourceManager.GetString("\'{0}\' is required!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; not found!.
        /// </summary>
        public static string @__0___not_found_ {
            get {
                return ResourceManager.GetString("\'{0}\' not found!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{3}&apos; must have a maximum of &apos;{1}&apos; characters!.
        /// </summary>
        public static string @__3___must_have_a_maximum_of___1___characters_ {
            get {
                return ResourceManager.GetString("\'{3}\' must have a maximum of \'{1}\' characters!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{3}&apos; must have at least &apos;{0}&apos; characters!.
        /// </summary>
        public static string @__3___must_have_at_least___0___characters_ {
            get {
                return ResourceManager.GetString("\'{3}\' must have at least \'{0}\' characters!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed in domain validation!.
        /// </summary>
        public static string Operation_failed_in_domain_validation_ {
            get {
                return ResourceManager.GetString("Operation failed in domain validation!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed in entity validation!.
        /// </summary>
        public static string Operation_failed_in_entity_validation_ {
            get {
                return ResourceManager.GetString("Operation failed in entity validation!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed in request validation!.
        /// </summary>
        public static string Operation_failed_in_request_validation_ {
            get {
                return ResourceManager.GetString("Operation failed in request validation!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        public static string Stores {
            get {
                return ResourceManager.GetString("Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful operation!.
        /// </summary>
        public static string Successful_operation_ {
            get {
                return ResourceManager.GetString("Successful operation!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful operation!.
        /// </summary>
        public static string Unsuccessful_operation_ {
            get {
                return ResourceManager.GetString("Unsuccessful operation!", resourceCulture);
            }
        }
    }
}
