const CREATE_API_SERVICE = 'CREATE_API_SERVICE';
const CREATE_API_FILTER = 'CREATE_API_FILTER';

const REQUEST_GETBYFILTER = 'REQUEST_GETBYFILTER';
const RECEIVE_GETBYFILTER = 'RECEIVE_GETBYFILTER';

const REQUEST_GETBYID = 'REQUEST_GETBYID';
const RECEIVE_GETBYID = 'RECEIVE_GETBYID';

const REQUEST_DELETE = 'REQUEST_DELETE';
const RECEIVE_DELETE = 'RECEIVE_DELETE';
const RECEIVE_DELETE_VALIDATIONS = 'RECEIVE_DELETE_VALIDATIONS';

const REQUEST_PATCH = 'REQUEST_PATCH';
const RECEIVE_PATCH = 'RECEIVE_PATCH';
const RECEIVE_PATCH_VALIDATIONS = 'RECEIVE_PATCH_VALIDATIONS';

const REQUEST_POST = 'REQUEST_POST';
const RECEIVE_POST = 'RECEIVE_POST';
const RECEIVE_POST_VALIDATIONS = 'RECEIVE_POST_VALIDATIONS';

const REQUEST_PUT = 'REQUEST_PUT';
const RECEIVE_PUT = 'RECEIVE_PUT';
const RECEIVE_PUT_VALIDATIONS = 'RECEIVE_PUT_VALIDATIONS';

const EXPIRE_COLLECTION = 'EXPIRE_COLLECTION';
const EXPIRE_ENTITY = 'EXPIRE_ENTITY';

export {
    CREATE_API_SERVICE, CREATE_API_FILTER,
    REQUEST_GETBYFILTER, RECEIVE_GETBYFILTER,
    REQUEST_GETBYID, RECEIVE_GETBYID,
    REQUEST_DELETE, RECEIVE_DELETE, RECEIVE_DELETE_VALIDATIONS,
    REQUEST_PATCH, RECEIVE_PATCH, RECEIVE_PATCH_VALIDATIONS,
    REQUEST_POST, RECEIVE_POST, RECEIVE_POST_VALIDATIONS,
    REQUEST_PUT, RECEIVE_PUT, RECEIVE_PUT_VALIDATIONS,
    EXPIRE_COLLECTION, EXPIRE_ENTITY
};