const APPLICATION_NAME_SET = 'APPLICATION_NAME_SET';
const APPLICATION_MENU_OPEN = 'APPLICATION_MENU_OPEN';
const APPLICATION_MENU_CLOSE = 'APPLICATION_MENU_CLOSE';

const APPLICATION_NOTIFICATION_ADD = 'APPLICATION_NOTIFICATION_ADD';
const APPLICATION_NOTIFICATION_SHOW = 'APPLICATION_NOTIFICATION_SHOW';
const APPLICATION_NOTIFICATION_CLOSE = 'APPLICATION_NOTIFICATION_CLOSE';

const APPLICATION_DIALOG_SHOW = 'APPLICATION_DIALOG_SHOW';
const APPLICATION_DIALOG_CLOSE = 'APPLICATION_DIALOG_CLOSE';
const APPLICATION_DIALOG_ADD_ACTION = 'APPLICATION_DIALOG_ADD_ACTION';

export {
    APPLICATION_NAME_SET,
    APPLICATION_MENU_OPEN,
    APPLICATION_MENU_CLOSE,
    APPLICATION_NOTIFICATION_ADD,
    APPLICATION_NOTIFICATION_SHOW,
    APPLICATION_NOTIFICATION_CLOSE,
    APPLICATION_DIALOG_SHOW,
    APPLICATION_DIALOG_CLOSE,
    APPLICATION_DIALOG_ADD_ACTION
}